name: Holy Manifesto
favicon: null
layout_spectrum: 0.35022
typography_spectrum: 0.25108
title: Helping men fulfill their intrinsic calling
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-17849267-9
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#142f3a'
    - '#7699a8'
    - '#bfc0b3'
    - '#335978'
    - '#8f7a79'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
