name: Manifesto
favicon: null
layout_spectrum: 0.1255
typography_spectrum: 0.7187
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#142f3a'
    - '#7699a8'
    - '#bfc0b3'
    - '#335978'
    - '#8f7a79'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
